apiVersion: apps/v1
kind: Deployment
metadata:
  name: applifting-backend-users
  labels:
    app: applifting-backend-users
spec: # This should be aligned with metadata, not nested under it
  replicas: 1
  selector:
    matchLabels:
      app: applifting-backend-users
  template:
    metadata:
      labels:
        app: applifting-backend-users
    spec:
      containers:
        - name: applifting-backend-users-deployment
          image: hhhhyy36/applifting-backend-users
          ports:
            # - containerPort: "2000"

          env:
            - name: PORT
              value: "2000"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASS
              value: "postgres"
            - name: POSTGRES_HOST
              value: "10.245.219.65"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "postgres"
            # - name: POSTGRES_SSL
            # value: "require"
